# Generated by Django 5.1.2 on 2024-11-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='tarjeta_principal',
            field=models.BooleanField(default=False),
        ),
    ]
