# Generated by Django 5.1.3 on 2024-11-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='sucursal',
        ),
    ]
