# Generated by Django 5.1.2 on 2024-11-21 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pesos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usd',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clienteEmisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to='clientes.cliente')),
                ('clienteReceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to='clientes.cliente')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.sucursal')),
            ],
        ),
    ]
