# Generated by Django 5.1.2 on 2024-11-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_pesos_cliente_usd_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='1234', max_length=100),
        ),
    ]
