# Generated by Django 5.1.2 on 2024-11-25 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_usuario_remove_cliente_apellido_remove_cliente_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clientes.usuario', unique=True),
        ),
    ]
