# Generated by Django 5.1.2 on 2024-11-27 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_rename_pagos_deuda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencia',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='transferencia',
            name='tipo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
