# Generated by Django 5.1.2 on 2024-11-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_remove_transferencia_sucursal_transferencia_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='recibida',
            field=models.BooleanField(default=False),
        ),
    ]
