# Generated by Django 5.1.3 on 2024-11-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
    ]
