# Generated by Django 5.1.3 on 2024-12-01 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_cliente_foto'),
        ('prestamos', '0003_alter_prestamo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.sucursal'),
        ),
    ]
