# Generated by Django 5.1.3 on 2024-12-01 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_cliente_foto'),
        ('empleados', '0004_alter_empleado_fecha_contratacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.sucursal'),
        ),
    ]
