# Generated by Django 5.1.3 on 2024-11-12 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_sucursal'),
        ('tarjetas', '0002_marcatarjeta_tarjeta_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='sucursal',
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='clientes.cliente'),
        ),
    ]
